import { motion } from 'framer-motion'
import { Download } from 'lucide-react'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export default function ExportButton({ result, docType, model }) {
  const handleExport = () => {
    if (!result) return
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const PW  = doc.internal.pageSize.getWidth()
    const riskColor = result.riskLevel === 'High' ? [220,38,38] : result.riskLevel === 'Medium' ? [217,119,6] : [22,163,74]

    // ---- PAGE 1: Cover ----
    doc.setFillColor(7, 8, 15)
    doc.rect(0, 0, PW, 297, 'F')

    doc.setTextColor(79, 172, 254)
    doc.setFontSize(32)
    doc.setFont('helvetica', 'bold')
    doc.text('🛡️ LexGuard AI', PW / 2, 48, { align: 'center' })

    doc.setTextColor(100, 116, 139)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text('Legal Risk Report — Powered by AI', PW / 2, 58, { align: 'center' })

    doc.setDrawColor(79, 172, 254)
    doc.setLineWidth(0.3)
    doc.line(30, 64, PW - 30, 64)

    const meta = [
      ['Document Type', docType?.replace(/_/g, ' ')?.replace(/\b\w/g, l => l.toUpperCase()) || '—'],
      ['AI Model',      model?.toUpperCase()],
      ['Generated',     new Date().toLocaleString()],
      ['Risk Score',    `${result.riskScore} / 100`],
    ]
    let y = 78
    doc.setFontSize(11)
    meta.forEach(([k, v]) => {
      doc.setTextColor(100, 116, 139)
      doc.setFont('helvetica', 'normal')
      doc.text(k + ':', 36, y)
      doc.setTextColor(241, 245, 249)
      doc.setFont('helvetica', 'bold')
      doc.text(v, 90, y)
      y += 9
    })

    // Big risk score
    doc.setFontSize(52)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...riskColor)
    doc.text(`${result.riskScore}`, PW / 2, 150, { align: 'center' })
    doc.setFontSize(16)
    doc.text(`${result.riskLevel?.toUpperCase()} RISK`, PW / 2, 164, { align: 'center' })

    // ---- PAGE 2: Summary + Pros/Cons ----
    doc.addPage()
    doc.setFillColor(7, 8, 15)
    doc.rect(0, 0, PW, 297, 'F')

    doc.setTextColor(79, 172, 254)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Summary', 20, 24)

    doc.setTextColor(200, 210, 220)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const summaryLines = doc.splitTextToSize(result.summary || '', PW - 40)
    doc.text(summaryLines, 20, 34)

    const prosConsY = 34 + summaryLines.length * 6 + 8
    autoTable(doc, {
      startY:     prosConsY,
      head:       [['✅ Pros', '❌ Cons']],
      body:       Array.from({ length: Math.max(result.pros?.length || 0, result.cons?.length || 0) }, (_, i) => [
        result.pros?.[i] || '',
        result.cons?.[i] || '',
      ]),
      styles:     { fontSize: 9, textColor: [200, 210, 220], fillColor: [15, 17, 23], cellPadding: 4 },
      headStyles: { fillColor: [25, 30, 50], textColor: [79, 172, 254], fontStyle: 'bold' },
      columnStyles: { 0: { textColor: [0, 245, 147] }, 1: { textColor: [248, 113, 113] } },
      theme:      'grid',
    })

    // ---- PAGE 3: Red Flags ----
    doc.addPage()
    doc.setFillColor(7, 8, 15)
    doc.rect(0, 0, PW, 297, 'F')

    doc.setTextColor(251, 191, 36)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('🚨 Red Flags', 20, 24)

    autoTable(doc, {
      startY:     32,
      head:       [['Clause', 'Explanation', 'Severity']],
      body:       (result.redFlags || []).map(f => [f.clause, f.explanation, f.severity?.toUpperCase()]),
      styles:     { fontSize: 9, textColor: [200, 210, 220], fillColor: [15, 17, 23], cellPadding: 4 },
      headStyles: { fillColor: [58, 42, 30], textColor: [251, 191, 36], fontStyle: 'bold' },
      theme:      'grid',
    })

    // ---- PAGE 4: Negotiation Tips ----
    doc.addPage()
    doc.setFillColor(7, 8, 15)
    doc.rect(0, 0, PW, 297, 'F')

    doc.setTextColor(79, 172, 254)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('💬 Negotiation Tips', 20, 24)

    let tipY = 36
    doc.setFontSize(10)
    ;(result.negotiationTips || []).forEach((tip, i) => {
      doc.setTextColor(79, 172, 254)
      doc.setFont('helvetica', 'bold')
      doc.text(`${i + 1}.`, 20, tipY)
      doc.setTextColor(200, 210, 220)
      doc.setFont('helvetica', 'normal')
      const tipLines = doc.splitTextToSize(tip, PW - 50)
      doc.text(tipLines, 28, tipY)
      tipY += tipLines.length * 6 + 4
    })

    // Footer
    const totalPages = doc.getNumberOfPages()
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p)
      doc.setFontSize(8)
      doc.setTextColor(100, 116, 139)
      doc.text('Generated by LexGuard AI. Not a substitute for professional legal advice.', PW / 2, 290, { align: 'center' })
      doc.text(`Page ${p} of ${totalPages}`, PW - 20, 290, { align: 'right' })
    }

    doc.save(`LexGuard_Report_${Date.now()}.pdf`)
  }

  return (
    <motion.button
      onClick={handleExport}
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.97 }}
      style={{
        width:        '100%',
        padding:      '12px 16px',
        borderRadius: 10,
        border:       '1px solid rgba(79,172,254,0.3)',
        background:   'rgba(79,172,254,0.1)',
        color:        'var(--accent)',
        fontWeight:   700,
        fontSize:     13,
        cursor:       'pointer',
        display:      'flex',
        alignItems:   'center',
        justifyContent: 'center',
        gap:          8,
        transition:   'all 200ms ease',
        fontFamily:   'inherit',
      }}
    >
      <Download size={16} />
      Download PDF Report
    </motion.button>
  )
}
